services:
  degiromatic:
    build:
      context: .
    container_name: degiromatic
    restart: no
    env_file: .env
    volumes:
      - ./data:/data
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
